### ISSUE TITLE
Add bullet points in the readme and make the content more readable

### ISSUE THREAD

**Issue by pratik9315** [pratik2315/Covi_resources#9]
Make the content inside readme more readable by adding bullet points, separating them by paragraphs etc.

**Comment by smscoder-7** [comment]
assign me please

**Comment by pratik9315** [comment]
@OmkarGeedh Here you go!

**Comment by smscoder-7** [comment]
@pratik2315 i asked. can i work on this?

**Comment by pratik9315** [comment]
Hey @smscoder-7 ! 
Its fine you can go ahead

**Comment by smscoder-7** [comment]
@pratik2315 already given PR. please check and merge
